language: crystal
cache: shards
crystal:
  - latest
  - nightly

script:
  - crystal spec --error-trace
  - crystal tool format --check

after_success:
  - crystal docs

deploy:
  provider: netlify
  site: 9d6236c2-9c11-41a1-8940-2c80391d0f7b
  cleanup: false
  dir: docs
  prod: true
  edge: true
  on:
    branch: master
